server:
  port: 8090
spring:
  cloud:
    function:
      definition: myConsumer;targetId
    stream:
      bindings:
        myConsumer-in-0:
          #topic -> app/type/[store_id]
          destination: kirke/foodcart/*/aggregate
        targetId-in-0:
          destination: kirke/foodcart/*/request
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55554
                msgVpn: default
                clientUsername: default
                clientPassword: default
